services:
    lmdi.links.listener:
        class: lmdi\links\event\listener
        arguments:
            - '@language'
            - '@config'
            - '@template'
        tags:
            - { name: event.listener }

